### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ragged'

### ISSUE THREAD

**Issue by anthonyyuan** [herbwood/face_liveness_detector#1]
Can u use tensorlow 1 ? because you use tensorflow.keras ,but i used tensorflow 1.14 and keras2.25

**Comment by herbwood** [comment]
Change the data_loder.py, trainer.py, utils.py and livenessnet.py files as follows:

- Comment out import `tensorflow as tf` and use `import keras`
- Then change the part that says `tf.keras` to `keras` 
ex) `tf.keras.layers.Conv2D` => `keras.layers.Conv2D`

It will probably work.
